services:
  - type: web
    name: PRIMEMUSIC-1
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 -m ShrutiMusic
    pythonVersion: 3.10.13
    autoDeploy: true

    envVars:
      API_ID: 
        value: 36582999
      API_HASH: 
        value: 7e0a1007a8fc56a275b2c61a42dd75de
      API_KEY:
        sync: false
      BOT_TOKEN:
        sync: false
      MONGO_DB_URI: 
        value: mongodb+srv://primemusic:PremGupta@primedb.xxxxx.mongodb.net/ShrutiMusic
      OWNER_ID:
        value: 8053529348
      OWNER_USERNAME:
        value: PREMGUPTA3M
      BOT_USERNAME:
        value: Prime_music07_bot
      UPSTREAM_REPO:
        value: https://github.com/Creatorpoint/PRIMEMUSIC.git
      STRING_SESSION:
        sync: false
      GIT_TOKEN:
        sync: false
      HEROKU_API_KEY:
        sync: false
      HEROKU_APP_NAME:
        sync: false
      LOG_GROUP_ID:
        value: -1003261923176
      SUPPORT_GROUP:
        value: https://t.me/PRIME_X_CHAT2
      SUPPORT_CHANNEL:
        value: https://t.me/PRIME_MUSIC08
      INSTAGRAM:
        value: https://www.instagram.com/prem_gupta_2m?igsh=MWFiNGx5NTl6Y3Npdw==
      YOUTUBE:
        value: https://youtube.com/@teamprimex-l9r?si=gqVLn6KqADdSgQAa
      GITHUB:
        value: https://github.com/Creatorpoint/PRIMEMUSIC.git
      DONATE:
        value: https://t.me/PRIME_MUSIC08/15
      START_IMG_URL:
        sync: false
